owner: devkraft-shashanksingh
repo: uptime-monitor

sites:
  - name: GIST QA API
    url: https://gist-qa.indegene.com/api/v1/health

  - name: Bayer QA
    url: https://bayer-ws-qa.indegene.com/bapi/v1/health

  - name: Bayer UAT
    url: https://bayer-ws-uat.indegene.com/bapi/v1/health

  - name: Bayer PROD
    url: https://bayer-ws.indegene.com/bapi/v1/health

  - name: AOR Debranded QA
    url: https://aor-debranded-demo.indegene.com/bapi/v1/health

  - name: AOR WS 
    url: https://aor-ws.indegene.com/bapi/v1/health

  - name: AOR WS 
    url: https://agents-comm-demo.indegene.com/bapi/v1/health


status-website:
  # Using GitHub Pages
  baseUrl: /uptime-monitor

  logoUrl: https://raw.githubusercontent.com/devkraft-shashanksingh/uptime-monitor/master/assets/upptime-icon.svg
  name: Indegene Server Status
  introTitle: "**Indegene Server Status**"
  introMessage: Real-time monitoring for Indegene services powered by Upptime.

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
