owner: devkraft-shashanksingh
repo: uptime-monitor

sites:
  - name: GIST QA API
    url: https://gist-qa.indegene.com/api/v1/health

status-website:
  # Using GitHub Pages
  baseUrl: /uptime-monitor

  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: GIST QA Status
  introTitle: "**GIST QA Status**"
  introMessage: Real-time monitoring for the GIST QA API powered by Upptime.

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
