owner: devkraft-shashanksingh
repo: uptime-monitor

sites:
  - name: GIST QA API
    url: https://gist-qa.indegene.com/api/v1/health
    
  - name: AOR QA API
    url: https://aor-ws.indegene.com/api/v1/health

  - name: Label Update QA
    url: https://label-update-qa.indegene.com/api/v1/health

status-website:
  # Using GitHub Pages
  baseUrl: /uptime-monitor

  logoUrl: https://raw.githubusercontent.com/devkraft-shashanksingh/uptime-monitor/master/assets/upptime-icon.svg
  name: Indegene Server Status
  introTitle: "**Indegene Server Status**"
  introMessage: Real-time monitoring for Indegene services powered by Upptime.

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
